CREATE TABLE retail_sales (
    transaction_id VARCHAR(20),
    customer_id VARCHAR(20),
    category VARCHAR(100),
    item VARCHAR(100),
    price_per_unit NUMERIC,
    quantity INTEGER,
    total_spent NUMERIC,
    payment_method VARCHAR(50),
    location VARCHAR(50),
    transaction_date DATE,
    discount_applied BOOLEAN
);

select * from retail_sales


/*1. What is the total revenue generated by the store?*/

SELECT SUM(total_spent) AS total_revenue
FROM retail_sales;

/*2. Which product category generates the highest revenue?*/

SELECT category,
       SUM(total_spent) AS revenue
FROM retail_sales
GROUP BY category
ORDER BY revenue DESC;

/*3. Which are the Top 5 revenue-generating products?*/

SELECT item,
       SUM(total_spent) AS revenue
FROM retail_sales
GROUP BY item
ORDER BY revenue DESC
LIMIT 5;

/*4. Who are the Top 10 customers by spending?*/

SELECT customer_id,
       SUM(total_spent) AS total_spending
FROM retail_sales
GROUP BY customer_id
ORDER BY total_spending DESC
LIMIT 10;

/*5. How much does an average customer spend?*/

SELECT AVG(customer_total)
FROM
(
    SELECT customer_id,
           SUM(total_spent) AS customer_total
    FROM retail_sales
    GROUP BY customer_id
) t;